### PR TITLE
refactor!: remove nvim-treesitter dependency

### PR DESCRIPTION
**Pull request by amaanq**
###### Description of changes

Remove the dependency of nvim-treesitter

I don't use nix so I don't know exactly how to run the tests/ensure it's all good

###### Things done

- [ ] Tested, as applicable:
  - [ ] Added plenary specs
  - [ ] Manually
- [x] Updated [CHANGELOG.md](../CHANGELOG.md) (if applicable).
- [x] Fits [CONTRIBUTING.md](https://github.com/MrcJkb/neotest-haskell/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by mrcjkb** [comment]
Thanks!

The prefix `refactor!` indicates that this is a breaking change.
I'm not sure it is, since this doesn't break the API or call any functions that break compatibility Or am I missing something?

**Comment by mrcjkb** [comment]
Sounds reasonable to me. Would you mind adding  a changelog entry (to an `## [Unreleased]` section, with a `POTENTIALLY BREAKING:` prefix)  and removing the notes about the dependency in the readme? :pray:

**Comment by amaanq** [comment]
Updated, a user will still need the haskell parser which *can* be installed via nvim-treesitter or by just supplying haskell.so in the rtp, see if that looks good

**Review by mrcjkb — DISMISSED** [review]
Thanks! :pray: Looks good to me.

**Comment by mrcjkb** [comment]
@all-contributors please add @amaanq  for code

**Comment by mrcjkb** [comment]
@amaanq I'll wait a few days before tagging a new release.

**Pull request merged**
